### ISSUE TITLE
Racial passiveselector and equipmentselector official support

### ISSUE THREAD

**Issue by TheRealDjmr** [TheRealDjmr/BG3ImprovedUI#136]
I've added in racial passiveselector support but I need a mod to use it

https://github.com/TheRealDjmr/BG3ImprovedUI/pull/88

Racial equipmentselector should also be supported and I would like to ensure that Race has the same features as class

**Comment by RandoRuda** [comment]
I'll take on some testing.

**Comment by RandoRuda** [comment]
Sorry for the late update. I had intended to update earlier.

# Racial Testing Update
- Utilised maiin branch, so let me know if I should've been using another.

## Equipment 
- Various tests on base races attempted.
- Unable to get weapons or musical instruments to show.

## Passives
- Have not begun; very distracted of late. Hoping to do some more testing whilst commuting this week.

**Comment by DungeonsAndSouls** [comment]
Did some testing for this,  since this update can drastically impact Fantastical Multiverse! So thank you for adding the selectpassives selector to Improved UI, now can also use it at levels above first so I really appreciated your work with the UI! 

### SelectPassives
![20231017184009_1](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/108700719/c40506c0-7d89-4c54-ada1-ea293ba8b025)
![20231017194159_1](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/108700719/56802c88-5e8d-4602-acf5-f58729ba0185)

Racial Passives works 100% furthermore it can work for levels above level 1. This means this UI for this feature has surpassed even Early Access. 


### SelectEquipment
![20231017194548_1](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/108700719/0dc2eab9-2d5f-4552-9261-143eaa52f05c)
As Rando stated above the SelectEquipment doesn't display on either level instead it just causes you to be unable to progress in the level-up screen. I tried it with 1st and 3rd levels but the result is the same regardless, you just get  "Choices Pending!" since it doesn't display in the UI it won't let you select an instrument or equipment so you can't confirm it. It's basically there but hidden still.

**Comment by RandoRuda** [comment]
> you just get "Choices Pending!" since it doesn't display in the UI it won't let you select an instrument or equipment so you can't confirm it. It's basically there but hidden still.

Indeed. It also also confirmed by setting the default values

> Racial Passives works 100% furthermore it can work for levels above level 1. This means this UI for this feature has surpassed even Early Access.

I have been so busy with IRL stuff that I have felt bad for being unable to devote enough time for this after agreeing to do some testing. Thank you so much for your testing and hard work.

**Comment by RandoRuda** [comment]
> I'm gonna knuckle in today and see if I can get at what's holding back Equipment here. 💪😤 I've also got a working first draft for selecting racial spells at level up (instead of only in CC) and I'm pretty confident it should coexist swimmingly even if/when there are hardcoded/prescribed racial feature spell(s), or other racial features, granted at the same level. 💃🏻

Thanks for looking into this.

If you like, feel free to let us know when you have a branch ready for some testing and I'll run it through a few cases.

**Comment by RandoRuda** [comment]
Testing the limits and it seems equipment does not currently seem to have the scroll bars working.

![image(1).png](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/122662331/3835314c-25aa-4dd3-a55d-0d40e54d0645)

**Comment by TheRealDjmr** [comment]
> Testing the limits and it seems equipment does not currently seem to have the scroll bars working.
> 
> ![image(1).png](https://user-images.githubusercontent.com/122662331/280881904-3835314c-25aa-4dd3-a55d-0d40e54d0645.png)

I've sorted this one in #207

**Comment by RandoRuda** [comment]
> > Testing the limits and it seems equipment does not currently seem to have the scroll bars working.
> > ![image(1).png](https://user-images.githubusercontent.com/122662331/280881904-3835314c-25aa-4dd3-a55d-0d40e54d0645.png)
> 
> I've sorted this one in #207

![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/122662331/f77038f1-01f1-40ae-a9fc-f33c41a870fa)

I am absolutely tickled.

**Comment by TheRealDjmr** [comment]
From the looks of things, Equipment is the last hurdle before Race has the same level of progression functionality compared to Class. I'll pick this up to try and complete the set I think

**Comment by TheRealDjmr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support selectors (spell, passive, skill, equipment) from Race in LevelUp](https://trello.com/c/GlVnBbMT/12-support-selectors-spell-passive-skill-equipment-from-race-in-levelup)

**Comment by TheRealDjmr** [comment]
It's been working ingame for a while, no changes to levelup in patch 6, I tested it earlier in CC and it was working then

**Comment by TheRealDjmr** [comment]
I'm closing this one off as i'm 99% sure that Racial Equipment is impossible, since Racial Equipment isn't a property available to us. Everything else is done
