### ISSUE TITLE
Keep name after interacting with the magic mirror

### ISSUE THREAD

**Issue by Mirimes** [TheRealDjmr/BG3ImprovedUI#166]
When using the magic mirror it resets the character's name to the default name (Tav, Dark Urge, etc). Would be better (if possible) to keep the character's name as behaviour.

**Comment by TheRealDjmr** [comment]
This only seems to happen with The Dark Urge, and it might be due to him being a custom origin. I was able to replicate this on an unmodded save.

I think Dark Urge would need to be treated as a 2nd Custom Origin (rather than a defined Origin you can customise) for this to change rather than any UI edits
