### ISSUE TITLE
Post-Patch 4, some users are seeing "empty" containers with invisible item icons

### ISSUE THREAD

**Issue by logical-fallazee** [TheRealDjmr/BG3ImprovedUI#171]
![USjNwNG](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/83232936/9680a0fb-8275-431f-a6ed-34264924e85f)

Some users are reporting an issue where "inventory in containers exist but you cant see them unless you hover over the space". Reports seem inconsistent at the moment; more data needed.
* Seems to only occur in non-character-inventory, environment containers
* One report of a user experiencing the issue _with_ IUI main but _without_ IUI Assets, and the issue was resolved by _adding_ IUI Assets (previous version)
* One report of a user experiencing the issue with previous version of Assets, updating to the newly released Assets (Patch 4 updated), and still experiencing the issue afterward
* Some reports of users not experiencing the issue with Assets (previous) and now experiencing the issue after updating to Patch 4 Assets, and reverting to previous version resolves the issue

**Comment by TheRealDjmr** [comment]
This seems to be due to the Patch 4 changes in Datatemplates.xaml - `<DataTemplate x:Key="Template.ItemEquipment" DataType="{x:Type ls:VMItem}">`

@logical-fallazee your changes are in line with Patch 4, and I'm unable to replicate this issue in Patch 4. I'm pretty sure this is going to be an issue if you're on Patch 3 with Patch 4 versions of ImprovedUI Assets, or on Patch 4 and haven't updated ImprovedUI Assets yet.

Happy to be sure though and keep this open just in case

**Comment by TheRealDjmr** [comment]
"weird thing - invisible inventory is fixed for me with core ui latest and assets downgraded to the patch 3 version. Super strange. With assets new patch 4 version, I get the invisible inventory issue.
I don’t have any other ui mods except better hotbar"

**Comment by TheRealDjmr** [comment]
Every time I come across this issue, it's the result of another mod that's conflicts with ImprovedUI, or they're not on Patch 4.
