### ISSUE TITLE
Action resource placeholder showing instead of true count.

### ISSUE THREAD

**Issue by Tek42** [TheRealDjmr/BG3ImprovedUI#286]
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/6154612/40114029-06cf-4e87-a981-e0f434cd1657)

Using the Firearms mod, when the resource is full it shows the number 6 (full resources) and one star. After first shot it shows the six stars shown in the screenshot. It doesn't change from those 6 stars even when the resource is depleted.  It appears to be using the placeholder image. Would it be possible to change this to show a numerical counter like it does when it's full?

**Comment by TheRealDjmr** [comment]
This was fixed in the latest version of ImprovedUI Assets - #274

When you have 6+ resources, it shows one star (representation of the action resource) and the numerical value

When you have 5 or fewer resources, it should only show 5 stars (how much of the action resource) with the representation of the resource hidden

If the "Ammo" resource should always have a numerical representation, an entry for handling the action resource can be added to ImprovedUI repository and I can add it to the next release, but these changes would need to originate from the mod owner - they would need to setup resource images etc for the best experience

Meanwhile, that screenshot should show 5 stars, and I'll see if there's anything I can do about it.

**Comment by TheRealDjmr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [6 stars instead of 5](https://trello.com/c/QcTDfF5L/129-6-stars-instead-of-5)

**Comment by TheRealDjmr** [comment]
Added in latest version of ImprovedUI Assets
![firearm shot controller](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/80291281/791a8363-4b95-4a0f-a31e-bc6904429112)
