### ISSUE TITLE
Resource points have disappeared from my hotbar

### ISSUE THREAD

**Issue by nicholaiTukanov** [TheRealDjmr/BG3ImprovedUI#356]
Thanks for such an amazing mod.

After using Appearance Edit Enhanced to respec to modded classes/subclasses, some of my characters are missing things like grit points/ammo (Exandrian Gunslinger), ALL their spell slots (Circle of Stars), and sorc points (Aberrant Mind). 

Note that only the icons are missing. Not like the old bug where the icon pictures are missing, but the entire spot where the resource should be is gone. 

However, the characters themselves are still able to use their resources, and my Circle of Stars druid is able to see the spell slots through the spell book.

For example, on my Exandrian Gunslinger, only my action, bonus, aptitude, and cantrips are showing up.
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/22804956/7cf09244-215b-4141-9e61-348122b5e08f)
I am missing the resources for my firearm ammo as well as my grit points.

Any help on debugging this issue would be greatly appreciated.

Again, thanks for making such an amazing mod.

**Comment by nicholaiTukanov** [comment]
I also found an old post on steam that details my same issue. However, I have the latest version of both Fantastical Multiverse and Artificer so that fix can't work for me :(

https://steamcommunity.com/app/1086940/discussions/3/3874840228865033676/

**Comment by TheRealDjmr** [comment]
Exandrian Gunslinger is supported, the other 2 are not. Grit points show correctly for me.

Circle of Stars has the action resource "Star Map Guiding Bolt Charge" and it hasn't been added to ImprovedUI, which is why you get the star. It's not listed [here](https://github.com/TheRealDjmr/BG3ImprovedUI/blob/main/Assets%20-%20Supported%20Mods.md) - however, the spell slots are the same as all Druids, they show correctly for me, so it sounds like something else going on.

Aberrant Mind has both spell slots and sorcery points showing correctly too

Either way, it's not an issue with this mod

**Comment by nicholaiTukanov** [comment]
> Either way, it's not an issue with this mod

Do you have any advice on how to debug this?
