### ISSUE TITLE
Action Points and spell slots are missing their UI icons

### ISSUE THREAD

**Issue by harlequinzeg0** [TheRealDjmr/BG3ImprovedUI#78]
Latest release causes the UI for these elements to disappear.

![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/2275463/50eec4bc-5f07-43e4-aa7e-1a62969b6764)

**Comment by nowitsabby** [comment]
I am also seeing this. Using BG3 Mod Manager to install

**Comment by mirrorhead-uk** [comment]
Also seeing this, used Vortex to install

**Comment by Daarka** [comment]
+1, also having this issue (Mod Manager used on my end).

**Comment by TheRealDjmr** [comment]
That's intentional. The image files have been moved to the appropriate mod for disk space

**Comment by Autentist** [comment]
There is an issue, beyond missing action icons.
I and several other people can't seem to select Cleric Subclasses in the selection screen. They are simply missing entirely.

**Comment by juumeijin** [comment]
I had this problem with "Cleric Subclasses" and/or "Expansion (Bladesinger Only)" with the one or all of the following other mods installed. "Better Character and Party Panels", "Better Containers", "Better Combat Log" or "Damage Preview". Having "Artificer class and all subclasses" installed with above mods would make them reappear again. Might be why some have issues while it's _fine_ for others.

A couple mods that don't show up as orange (is this something each modder has to manually mark?) in BG3MM breaks it as well despite being in the inactive list. "Deity for All" with only Cleric, Bladesinger and Artificer but works if the above ui mods are folder as well. "Monk 5e Adjustments"- Mercy patch breaks it even with Artificer and the above ui mods.
I don't expect everything to work together but I thought I'd mention them since they worked with the prior version and could clue you in on what's wrong.

**Comment by Gladoffel** [comment]
I have a similiar problem with neither the Shadar-Kai subrace Icon nor the Action Ressource Icons appearing with only the mods required by the Shadar-Kai mod installed.

**Comment by Ksenon-UTG** [comment]
Had the same issue, removed 3.7 main and assets, reinstalled 3.6 and 3.6.1 assets - working ok
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/9863245/78bbd74f-dfb3-416f-a6b1-a41e3d9a7e1a)

**Comment by Daarka** [comment]
> I'm investigating why this is only affecting certain users

I've seen several folks on Nexus say following these instructions "fixed" it for them. Before I do the same, do you, as the actual mod author, recommend this or should I just sit tight and wait for a fix?
![Screenshot](https://i.gyazo.com/23a7cb3eb63e6f435cfd54071ae15b15.png)

**Comment by TheRealDjmr** [comment]
> > I'm investigating why this is only affecting certain users
> 
> I've seen several folks on Nexus say following these instructions "fixed" it for them. Before I do the same, do you, as the actual mod author, recommend this or should I just sit tight and wait for a fix? ![Screenshot](https://camo.githubusercontent.com/af5d05764cf8c03b479844beb1955058df1784e9c10d9eb87735a2325d6c2722/68747470733a2f2f692e6779617a6f2e636f6d2f32336137636233656236336536663433356366643534303731616531356231352e706e67)

Anyone can try that for personal use

I'm looking into a permanent fix, but I'm travelling currently so have limited things I can test.

**Comment by Daarka** [comment]
Putting this here for the benefit of anyone poking around looking for solutions in the meantime:
A lot of folks have reported the issue being fixed on their end by using the prior version of the Assets file with the newest version of the main core file. Djmr has re-enabled 3.6 to be downloaded for now on the Nexus page:
![Screenshot](https://i.gyazo.com/8762f637f472ef434759569b1a6c9010.png)

**Comment by Kuroshiro2573** [comment]
For some reason installing the Hexblade subclass fixed it for me. Was just using Artificer before out of the mods that require the assets.

**Comment by Linne95** [comment]
> For some reason installing the Hexblade subclass fixed it for me. Was just using Artificer before out of the mods that require the assets.

This worked for me aswell, thank you

**Comment by TheRealDjmr** [comment]
Update - should hopefully have a solution out tomorrow

**Comment by TheRealDjmr** [comment]
Fixed in 3.8 - https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.8
